apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gourjagruti1799/test-argocd.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true          # Prune resources that are no longer defined in the Git repo
      selfHeal: true       # Automatically heal if any resource becomes out-of-sync
  helm:
    values: |
      # You can include your Helm values here if you're using Helm charts
  # Optional: Specify resource request/limit if using Argo CD with Helm
